### ISSUE TITLE
Ticket CSS

### ISSUE THREAD

**Issue by caillou** [swissjeese/swissjeese.github.io#3]
![screen shot 2015-04-14 at 11 20 25](https://cloud.githubusercontent.com/assets/46739/7133921/5dcacf56-e298-11e4-8cfc-0df58e1ef094.png)

**Comment by caillou** [comment]
@lejoe do you have time to look into that?

**Comment by lejoe** [comment]
What exactly do you want to improve?
The white lines the should not cross the dotted one?

**Comment by caillou** [comment]
![01_homepage_psd___200___bg__rgb_8_](https://cloud.githubusercontent.com/assets/46739/7134446/31a9af50-e29d-11e4-9ae4-2d885d9d096a.png)

* Lines start at the end of the word, centered
* Continue is not a button

**Comment by lejoe** [comment]
Ok, improved it:
![image](https://cloud.githubusercontent.com/assets/1759/7135077/85036eec-e2a3-11e4-8250-bfccbcec1de9.png)


Still a bug on medium screens. The rows get two lines and the background line is not aligned anymore:
![image](https://cloud.githubusercontent.com/assets/1759/7135092/ab52ea96-e2a3-11e4-8064-7818eaf9f2d5.png)
